language: go

go:
  - 1.14.x
  - 1.15.x

jobs:
  include:
    - go: 1.15.x
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2
        - golangci-lint run

env:
  - GO111MODULE=on

install:
  - go get -d -t ./...

script:
  - go test -v ./...
