---
version: 2.1

executors:
  go-build:
    docker:
      - image: quay.io/getpantheon/go-build:latest
        auth:
          username: $QUAY_USER
          password: $QUAY_PASSWD
commands:
  save-go-mod-cache:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod

  restore-go-mod-cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.mod" }}

  save-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - ./

  restore-workspace:
    steps:
      - attach_workspace:
          at: .

jobs:
  test:
    executor: go-build
    steps:
      - checkout
      - restore-go-mod-cache
      # commands
      - run: go get
      - run: golangci-lint run -E goimports -v
      - run: go test -v ./pollwatcher/...
      - run: go test -v ./fswatcher/...
      - run: go test -v .
      - run: go test -run=XXX -bench=.
      # persist
      - save-go-mod-cache
      - save-workspace

  tag-version:
    executor: go-build
    steps:
      - restore-workspace
      # commands
      - run: |
          curl -s https://api.github.com/repos/pantheon-systems/autotag/releases/latest | \
            grep browser_download | \
            grep -i linux | \
            cut -d '"' -f 4 | \
            xargs curl -o ~/autotag -L \
            && chmod 755 ~/autotag
      - run: ~/autotag
      - run: |
          # stdout and stderr redirected to null to prevent leaking the token on error.
          # to debug failures re-run this job with ssh
          git push -q --tags \
            --repo=https://${GITHUB_TOKEN}@github.com/pantheon-systems/certinel \
            >/dev/null 2>&1

workflows:
  version: 2
  primary:
    jobs:
      - test
      - tag-version:
          requires:
            - test
          filters:
            branches:
              only:
                - master
