name: Test
on:
  - pull_request
  - push
jobs:
  unit:
    strategy:
      matrix:
        go: ["stable", "oldstable"]
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    name: "Go ${{ matrix.go }} (${{ matrix.os }}) Test"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install Watchman (apt)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: DEBIAN_FRONTEND=noninteractive sudo apt install -y watchman && watchman -v
      - name: Install Watchman (brew)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install watchman && watchman -v
      - name: Install Watchman (chocolatey)
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install watchman && watchman.exe -v
      - run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - uses: dominikh/staticcheck-action@v1
        with:
          build-tags: suite
          install-go: false
